Smusand3
aws-samples/amazon-rds-proxy-multitenant-load-test pull request #13
Opened 2021-04-29 18:12 UTC by samsanders23

Narrowing of security group outbound for add users proxy lambda.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-30 10:02 UTC, rezabekf requested changes

2021-04-30 10:02 UTC, rezabekf commented on .pre-commit-config.yaml
> +#     files: \.template$
Hi Sam, any chance to fix your local development environment so we don't have to keep reverting this change?

2021-04-30 10:02 UTC, rezabekf commented on cfn/add-users.template
> +          ToPort: 3306
Does this change works for both Proxy and NoProxy clusters?

2021-05-04 15:13 UTC, samsanders23 commented on cfn/add-users.template
> +          ToPort: 3306
Should do, it was working during my test.

2021-05-04 15:13 UTC, samsanders23 commented on .pre-commit-config.yaml
> +#     files: \.template$
I can't find a way unfortunately

2021-05-05 09:30 UTC, rezabekf approved these changes
LGMT

2021-05-05 09:30 UTC, merged