Smusand2/proxyreaderendpoint
aws-samples/amazon-rds-proxy-multitenant-load-test pull request #17
Opened 2021-05-14 13:27 UTC by samsanders23

Re-routing Lambda requests to the RDS Proxy reader endpoint instead, to utilise a new RDS Proxy feature. This also creates 2 Aurora readers to route the read requests to. Tested and is functional.

Also the CloudWatch dashboard was updated to reduce the period interval from 300 to 60 seconds

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-14 15:16 UTC, rezabekf requested changes

2021-05-14 15:16 UTC, rezabekf commented on cfn/dashboard.template
> +          - !Sub '", {"label": "Proxy"}]], "region": "${AWS::Region}", "title": "Lambda Concurrent executions", "view": "timeSeries", "stacked": false, "period": 60, "stat": "Maximum", "yAxis": {"lef
Are that data send to dashboard every minute? Thought the default time is every 5 minutes.

2021-05-14 15:16 UTC, rezabekf commented on cfn/rds.template
> +      PubliclyAccessible: false
What are these additional DBs used for? Are they read instances? If yes, can you Change naming to, for example `DbReadInstance1` | `DbWriteInstance1`

2021-05-14 15:16 UTC, rezabekf commented on src/functions/noproxy/cr_add_users_noproxy.py
> -    logger.info("Got Create")
why is this deleted?

2021-05-14 15:16 UTC, rezabekf commented on src/functions/proxy/cr_add_users_proxy.py
> -    logger.info("Got Create")
why was this removed?

2021-05-14 15:16 UTC, rezabekf commented on cfn/rds.template
> -                    kms:ViaService: !Sub secretsmanager.${AWS::Region}.amazonaws.com
wasn't this removed in PR #16 ?

2021-05-14 15:39 UTC, samsanders23 commented on cfn/dashboard.template
> +          - !Sub '", {"label": "Proxy"}]], "region": "${AWS::Region}", "title": "Lambda Concurrent executions", "view": "timeSeries", "stacked": false, "period": 60, "stat": "Maximum", "yAxis": {"lef
The granularity can be increased to every minute.

2021-05-14 15:40 UTC, samsanders23 commented on cfn/rds.template
> +      PubliclyAccessible: false
Yes, I'll update this accordingly

2021-05-14 15:41 UTC, samsanders23 commented on src/functions/noproxy/cr_add_users_noproxy.py
> -    logger.info("Got Create")
Removed as it's unnecessary when the lambda logs are analysed, the message 'got create' is confusing. This won't be needed in the final form

2021-05-17 17:45 UTC, samsanders23 commented
Also updated CW Dashboard accordingly, to use the reader endpoints, rather than the aurora writer instance.

2021-05-18 08:20 UTC, rezabekf commented on src/functions/noproxy/cr_add_users_noproxy.py
> -    logger.info("Got Create")
Its actual opposite, the logging is there to help to see what function within lambda was called, e.g. on creating stack you will see message "Got Create", on updating stack "Got Update and on deleting stack "Got Delete", I dont see the reason to remove this, as it helps troubleshoot `crhelper` calls in CWL. For more info see https://pypi.org/project/crhelper/

2021-05-18 08:21 UTC, rezabekf commented on src/functions/proxy/cr_add_users_proxy.py
> -    logger.info("Got Create")
Same as above

2021-05-18 08:24 UTC, rezabekf requested changes

2021-05-18 08:24 UTC, rezabekf commented on .pre-commit-config.yaml
> +    files: \.template$
Perfect

2021-05-18 10:47 UTC, samsanders23 commented on src/functions/noproxy/cr_add_users_noproxy.py
> -    logger.info("Got Create")
I suppose I'm confused by the wording, what do you mean by 'Got create'? Do you mean 'Create function initialized', or 'Users created'? If so I'll change to this (and the delete and update statements accordingly) and update the PR

2021-05-18 11:07 UTC, rezabekf commented on src/functions/noproxy/cr_add_users_noproxy.py
> -    logger.info("Got Create")
It's relevant to the function initialized. Check the link I have attached.

2021-05-18 14:46 UTC, samsanders23 commented on src/functions/noproxy/cr_add_users_noproxy.py
> -    logger.info("Got Create")
I see the purpose, just not the wording. Added back anyway.

2021-05-18 15:58 UTC, rezabekf approved these changes
LGMT

2021-05-26 15:02 UTC, merged