Smusand2/readme
aws-samples/amazon-rds-proxy-multitenant-load-test pull request #18
Opened 2021-05-26 16:06 UTC by samsanders23

Small changes, just the readme (with a cost breakdown), + reducing the size of the Aurora write node for cost purposes.

Update: also several security alterations, in line with a Security Review.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-26 18:16 UTC, rezabekf commented on cfn/rds.template
> +      DBInstanceClass: db.t3.small
This is not a right place to define instance class. This proposed change will hard code the value, make it difficult in a future to change the size. If you need to update the size, please change the default value here https://github.com/aws-samples/amazon-rds-proxy-multitenant-load-test/blob/613bf844bcee3310d15c1cdb8a9c27bb2f4d2c6e/cfn/main.template#L87

2021-05-26 18:18 UTC, rezabekf requested changes
See the inline comment for `rds.template`

2021-05-26 18:21 UTC, rezabekf commented on cfn/rds.template
> +      DBInstanceClass: db.t3.small
If you need to introduce different sizes for "Reader" and "Writer" nodes, I would recommend to do so in a same fashion it is done now; as a parameter passed from main stack down to rds stack.

2021-05-28 17:33 UTC, samsanders23 commented on cfn/rds.template
> +      DBInstanceClass: db.t3.small
Done

2021-06-09 15:48 UTC, samsanders23 commented
All changes fixed, please approve for merge

2021-06-09 18:34 UTC, rezabekf requested changes

2021-06-09 18:34 UTC, rezabekf commented on Makefile
> +		CIDRRange=$(CIDR_RANGE) \
Please add any overrides to `.custom.mk.example` too as this is used to define your parameters.

2021-06-09 18:34 UTC, rezabekf commented on README.md
> +|DBWriterClass|db.t3.small|The database instance class for the Proxy and No Proxy VPC Amazon Aurora Writer, for example db.m5.large.|
Please change "for example" to "db.t3.small" to reflect the default value.

2021-06-09 18:34 UTC, rezabekf commented on cfn/access-function.template
> -    Type: String # Has to be type String as NoProxy has 'NA' value
Why was this removed? It is rather important comment if anyone wants to modify template. But yeah, can be removed if you think it is not needed.

2021-06-10 08:46 UTC, samsanders23 commented on cfn/access-function.template
> -    Type: String # Has to be type String as NoProxy has 'NA' value
Nick requested for me to remove this and all other comments in this template

2021-06-10 08:49 UTC, samsanders23 commented
All changes implemented / commented on

2021-06-10 09:27 UTC, rezabekf commented on README.md
> +|DBWriterClass|db.t3.medium|The database instance class for the Proxy and No Proxy VPC Amazon Aurora Writer, for example db.m5.large.|
```suggestion
|DBWriterClass|db.t3.medium|The database instance class for the Proxy and No Proxy VPC Amazon Aurora Writer, for example db.t3.medium.|
```

2021-06-10 09:33 UTC, rezabekf commented
> All changes implemented / commented on

There is still missing override parameter in `.custom.mk.example`. I will push the change myself to not go back and forth.

2021-06-10 09:42 UTC, rezabekf approved these changes
LGMT

2021-06-10 09:46 UTC, merged