Sam2/managedpolicies
aws-samples/amazon-rds-proxy-multitenant-load-test pull request #21
Opened 2021-06-23 15:45 UTC by samsanders23

As with IAM Guidelines, inline policies have been switched to Customer-managed policies. The permissions are identical as before. There is also a change to add API Gateway Access Logs.

Everything has been tested and is working.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-24 13:40 UTC, rezabekf requested changes

2021-06-24 13:40 UTC, rezabekf commented on cfn/access-function.template
> -      Policies:
Not sure why Inline policy was changed to managed as inline policy allowed to maintain strict one-to-one relationship between a policy and the identity that it's applied to. I think inline policy makes more sense as it makes sure that permissions in the policy cannot be inadvertently attached to the wrong identity.

Managed policy will be more suitable for it's re-usability, which is not the case in this instance. [More info on scenario how to choose correct policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#choosing-managed-or-inline)

2021-06-24 13:40 UTC, rezabekf commented on cfn/add-users.template
> -  LambdaAddUsersRole:
Same as above

2021-06-24 13:40 UTC, rezabekf commented on cfn/main.template
> +      ResourceTags: rds-iam
This map is not used anywhere. Also, if needed, we should reuse existing `ResourceTags` parameter as it distinguish between different resources.

2021-06-24 15:17 UTC, samsanders23 commented on cfn/access-function.template
> -      Policies:
The guidance from the IAM review was to use managed policies wherever possible, the code may be sent back otherwise. Some of the policies referenced in this and the other templates are reusable (for instance the XrayServiceAccessPolicy and the VPCSeviceAccessPolicy, which could be attached to any VPC-based Lambda), and in other instances they provide a template that the customer can copy and modify into another managed policy. Since managed policies rather than inline, except in rare circumstances (and I do not believe this is one of those circumstances) are a best practice, it makes sense to be using them. Also, because of the naming convention used for the managed policies created, I think this significantly reduces the risk of inadvertently attaching a policy to the wrong identity.

2021-06-24 15:19 UTC, samsanders23 commented on cfn/main.template
> +      ResourceTags: rds-iam
Good spot, I forgot to remove this.

2021-06-25 07:44 UTC, rezabekf commented on cfn/access-function.template
> -      Policies:
Fair enough, If the IAM review suggest managed policies, I am fine with that. Thanks for the explanation.

2021-06-25 07:47 UTC, rezabekf approved these changes
LGMT

2021-06-25 07:48 UTC, merged