rezabekf/cfn nag patch 02
aws-samples/amazon-rds-proxy-multitenant-load-test pull request #5
Opened 2021-03-29 10:57 UTC by rezabekf

*Description of changes:*
This PR addresses few warnings highlighted by cfn_nag. VPC Flow logs were added as optional parameter. MapPublicIpOnLaunch has been removed from Public Subnets and only instance required to have a routable IPv4 address has EIP assigned. Warning for Secrets manager secret and CloudWatch Logs custom managed key (CMK) has been disabled, see the reason at `ci/cfn_nag_blocklist.yaml`

2021-03-29 12:35 UTC, HieronymusLex requested changes

2021-03-29 12:35 UTC, HieronymusLex commented on ci/cfn_nag_blocklist.yaml
> +RulesToSuppress:
Do we need to suppress these? If they're warnings I'd rather they were still flagged for visibility since they won't fail any CI

2021-03-29 12:35 UTC, HieronymusLex commented on ci/cfn_nag_blocklist.yaml
> +  reason: >
can't we explicitly specify the default AWS managed secrets manager key alias to prevent this warning?

2021-03-29 12:38 UTC, rezabekf commented on ci/cfn_nag_blocklist.yaml
> +RulesToSuppress:
Ok, i will remove the suppression.

2021-03-29 12:42 UTC, rezabekf commented on ci/cfn_nag_blocklist.yaml
> +  reason: >
The issue is, if its a first time you creating secret with default key, the alias `aws/secretsmanager` or arn doesn't exist until it is created when the key is created. In short, you can not reference the key before the resource is created (and the default key is created under the hood.
```
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        ExcludePunctuation: true
        GenerateStringKey: password
        SecretStringTemplate: '{"username": "admin"}'
```

2021-03-29 14:29 UTC, HieronymusLex commented on ci/cfn_nag_blocklist.yaml
> +  reason: >
you can reference AWS managed keys before the first time they're used using the alias `alias/aws/secretsmanager` - I tested this today and confirmed it works

2021-03-29 16:10 UTC, rezabekf commented on ci/cfn_nag_blocklist.yaml
> +  reason: >
Thanks Nick ,i have pushed the change.

2021-03-29 16:37 UTC, HieronymusLex commented on cfn/vpc.template
> +                Resource: arn:aws:logs:*:*:*
does this need ot be so permissive? e.g. can we use the flow log group name and account ID since we know both of those?

2021-03-29 17:26 UTC, rezabekf commented on cfn/vpc.template
> +                Resource: arn:aws:logs:*:*:*
Thanks Nick, I have narrowed it down as suggested 👍

2021-03-30 07:58 UTC, HieronymusLex approved these changes

2021-03-30 08:40 UTC, merged