rezabekf/cfn nag patch 3
aws-samples/amazon-rds-proxy-multitenant-load-test pull request #6
Opened 2021-04-01 13:55 UTC by rezabekf

*Description of changes:*
This PR scopes down egress rules where possible. Please see in the comments the rules that weren't scoped down.

2021-04-01 14:05 UTC, rezabekf commented
I wasn't able to figure out how to scope [down this egress rule](https://github.com/aws-samples/amazon-rds-proxy-multitenant-load-test/blob/03f8f8d695a91c9ac268c39fa9988470001a30d8/cfn/add-users.template#L141-L149)

 have tried:
- restricting to both SG group and port 3306 - fail
- restricting to SG and have all ports open - fail
- restricting to port 3306 and have CIdrIp open to world -fail

2021-04-01 14:08 UTC, rezabekf commented
I have tried to restrict the [following egress rule](https://github.com/aws-samples/amazon-rds-proxy-multitenant-load-test/blob/03f8f8d695a91c9ac268c39fa9988470001a30d8/cfn/rds.template#L105-L113)

Two issues are happening here:
- it introduces circular dependency between `RDSSecurityGroup` and `ProxySecurityGroup` as the first one is `Ref` in the second one already.
- there is a problem when creating conditional statement for `RDSSecurityGroup`
```
RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      SecurityGroupEgress: !If
        - IsRDSProxy
        - - DestinationSecurityGroupId: !Ref ProxySecurityGroup
          - CidrIp: 0.0.0.0/0
            Description: Allow db outbound traffic
            IpProtocol: tcp
            FromPort: 3306
            ToPort: 3306
      VpcId: !Ref VpcID
```
The same code is used for both Proxy and No Proxy database and when NO proxy database is created the `cfn-lint` highlights the issue that resource `ProxySecurityGroup` may not be available when condition `IsRDSProxy` is False

I can mitigate this to add dedicated Security groups for Proxy and NoProxy db and have couple conditions to decide what gets created when
```
Conditions:
  IsRDSProxy: !Equals [!Ref CreateRDSProxy, true]
  IsNotRDSProxy: !Equals [!Ref CreateRDSProxy, false]
```
However, the NonProxy SG will still have egress open to the world, but I guess i can scope down port to 3306.

Port scoped down, see commit below.

2021-04-08 12:20 UTC, HieronymusLex requested changes

2021-04-08 12:20 UTC, HieronymusLex commented on cfn/ec2.template
> +          Description: Allow http inboud traffic
```suggestion
          Description: Allow http inbound traffic
```

2021-04-08 12:20 UTC, HieronymusLex commented on cfn/ec2.template
> +          FromPort: 51
port 53 and UDP required

2021-04-08 12:20 UTC, HieronymusLex commented on cfn/ec2.template
> +        - CidrIp: 0.0.0.0/0
is 0.0.0.0/0 required here if not using custom dns resolvers?

2021-04-08 12:34 UTC, rezabekf commented on cfn/ec2.template
> +          FromPort: 51
Fixed port number and added UDP protocol

2021-04-08 12:35 UTC, rezabekf commented on cfn/ec2.template
> +        - CidrIp: 0.0.0.0/0
Updated to Amazon provided DNS server.

2021-04-08 15:13 UTC, HieronymusLex approved these changes

2021-04-09 10:05 UTC, merged