Scope DB access
aws-samples/amazon-rds-proxy-multitenant-load-test pull request #8
Opened 2021-04-12 20:19 UTC by rezabekf

*Description of changes:*
This PR scopes down lambda access to DB instances. Also the STS IAM role inline policy is given better name.

2021-04-15 09:08 UTC, HieronymusLex commented on cfn/add-users.template
> +          PASSWORD: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DBInstanceIdentifier}/user
what's going on here with this env var named PASSWORD?

2021-04-15 09:13 UTC, HieronymusLex requested changes

2021-04-15 09:13 UTC, HieronymusLex commented on cfn/add-users.template
>          - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
I don't think FullAccess is required

2021-04-15 09:13 UTC, HieronymusLex commented on cfn/add-users.template
> +                - ec2:DeleteNetworkInterface
can DeleteNetwork interface be scoped down?

2021-04-15 09:13 UTC, HieronymusLex commented on cfn/add-users.template
> +                - secretsmanager:TagResource
does it not need untag resource too (e.g. if there's an update which causes a tag change)?

2021-04-15 09:13 UTC, HieronymusLex commented on cfn/add-users.template
> +                - ec2:DeleteNetworkInterface
as above

2021-04-15 09:13 UTC, HieronymusLex commented on cfn/add-users.template
> +        - Version: "2012-10-17"
It'd probably be better to create this as a separate policy resource and then attach it to both these lambdas to avoid copy/pasta

2021-04-15 09:13 UTC, rezabekf commented on cfn/add-users.template
> +          PASSWORD: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DBInstanceIdentifier}/user
@samsanders23 can you elaborate please?

2021-04-15 09:16 UTC, rezabekf commented on cfn/add-users.template
>          - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
Yes, i will scope this down in the upcoming patch.

2021-04-15 09:41 UTC, samsanders23 commented on cfn/add-users.template
> +          PASSWORD: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DBInstanceIdentifier}/user
I no longer think this is a required env variable, as I can't see it being referenced in the lambda itself, so can be removed.

2021-04-15 10:34 UTC, rezabekf commented on cfn/add-users.template
> +          PASSWORD: !Sub arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DBInstanceIdentifier}/user
env var PASSWORD has been removed

2021-04-15 10:35 UTC, rezabekf commented on cfn/add-users.template
>          - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
The RDS data access wasn't required at all. Removed

2021-04-15 10:36 UTC, rezabekf commented on cfn/add-users.template
> +        - Version: "2012-10-17"
Done

2021-04-15 13:57 UTC, rezabekf commented on cfn/add-users.template
> +                - ec2:DeleteNetworkInterface
I have tried to scope this down to resource `arn`. I have not managed to figure out why it doesn't work. Had following Resource (even the one below, which is super open fails in https://policysim.aws.amazon.com/home/index.jsp#roles
```
            "Resource": [
                "arn:aws:ec2:*:*:subnet/*",
                "arn:aws:ec2:*:*:security-group/*",
                "arn:aws:ec2:*:*:network-interface/*"
```

2021-04-15 14:01 UTC, rezabekf commented on cfn/add-users.template
> +                - secretsmanager:TagResource
No need to untag, as there is no action on CFN update. The lambda runs exactly once. Tags are part of the lambda function itself and the Tag value is hardcoded, see `src/functions/proxy/cr_add_users_proxy.py` lines 36-38

@samsanders23 could this be improved? maybe pass the tag value as env variable?

2021-04-15 14:02 UTC, rezabekf commented on cfn/add-users.template
> +                - ec2:DeleteNetworkInterface
same issue as above

2021-04-19 13:25 UTC, HieronymusLex approved these changes

2021-04-19 13:40 UTC, merged